### ISSUE TITLE
modular (Java 9) version

### ISSUE THREAD

**Issue by negste** [jIconFont/jiconfont#2]
Using more than one icon set in the same *modular* project is not possible because the package "jiconfont.icons" is split between the different projects (assuming one wants to put all the jars in the module path and use them as "automatic modules"). One solution could be to change package declaration in each one of the icon set projects, while keeping the overall structure of jiconfont non modular; otherwise, make jiconfont modular.

**Comment by caduandrade** [comment]
I started doing it before I saw your "pull request" ;-)

**Comment by caduandrade** [comment]
Done. I just deployed to Maven Central. It's will take a while to be available.

New versions:
- jiconfont-bundle: 1.4.0
- jiconfont-font_awesome: 4.7.0.1
- jiconfont-google_material_design_icons: 2.2.0.2
- jiconfont-open_iconic: 1.1.1.3
- jiconfont-elusive: 2.0.3
- jiconfont-entypo: 2.0.3
- jiconfont-typicons: 2.0.7.1
