### ISSUE TITLE
Icons not getting antialiased / appearing blurry

### ISSUE THREAD

**Issue by HiddenMachine3** [jIconFont/jiconfont#3]
There appears to be alot of distortion and artifacts when using small icons in JLabels and JButtons.
Here is the code I am using to test this:

```java
import com.formdev.flatlaf.FlatDarculaLaf;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

import javax.swing.*;
import java.awt.*;

public class Main {
    public static void main(String[] args) throws UnsupportedLookAndFeelException {
//        LookAndFeel laf = new NimbusLookAndFeel();
        LookAndFeel laf = new FlatDarculaLaf();
        UIManager.setLookAndFeel(laf);
        UIManager.put(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        UIManager.put("useSystemAAFontSettings", "on");
        UIManager.put("swing.aatext", "true");
        System.setProperty("awt.useSystemAAFontSettings","on");
        System.setProperty("swing.aatext", "true");
        UIManager.getDefaults().put(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        IconFontSwing.register(FontAwesome.getIconFont());

        JFrame frame = new JFrame("Test Window");
        JPanel content = new JPanel(new BorderLayout());

        JButton button = new JButton("Hello");
        button.setPreferredSize(new Dimension(100, 50));
        button.setIcon(IconFontSwing.buildIcon(FontAwesome.ARROW_LEFT, 40));
        content.add(button, BorderLayout.CENTER);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(content);
        frame.pack();
        frame.setVisible(true);
    }
}
```

This doesn't seem to work on Windows 10. I am using [Jiconfont ](https://github.com/jIconFont/jiconfont)to create the icons from [FontAwesome](https://stackoverflow.com/a/35464118/16348170) . This issue seems to be present regardless of the LookAndFeel.

This is the result I am getting, where the anti aliasing is not working on the icons:
![image](https://user-images.githubusercontent.com/108694711/200036293-1d17ee7f-9d77-49ec-9abe-64360b0eed04.png)
![image](https://user-images.githubusercontent.com/108694711/200036516-234af3a4-3045-4d60-9fb5-fca97859a560.png)  
![image](https://user-images.githubusercontent.com/108694711/200052892-1490e796-555a-43e1-ab6f-0b2b0ecee1c1.png)

**Comment by HiddenMachine3** [comment]
Please tell me a way to work around this. A workaround suggested by someone on [stackoverflow ](https://stackoverflow.com/questions/24177348/font-awesome-with-swing), but that just makes it more verbose  
Edit: it seems that the above answer also doesn't have antialiasing.
![image](https://user-images.githubusercontent.com/108694711/200075231-0d332069-7101-42ae-ab8f-46d03302b332.png)

I'm beginning to think that it might just have to do with the jdk itself, or the OS I'm using to run this

**Comment by HiddenMachine3** [comment]
The problem seems to be deeper than I thought. 

I just tested the app on a different OS : Ubuntu , and the antialiasing is actually working.

![image](https://user-images.githubusercontent.com/108694711/200110561-3017e157-b88b-43d9-a6a8-f812284685e0.png)

The antialiasing didn't work on Windows, but did work on Ubuntu. 

I'm starting to think that its probably a problem with how the jdk performs antialiasing based on OS, or maybe how jIconFont performs antialiasing based on OS, or some OS forced featured that controls antialiasing.

**Comment by HiddenMachine3** [comment]
I'm using [ikonli](https://kordamp.org/ikonli/) now, as this issue is a bummer. Someone pointed out to me that the [problem is in jiconfont itself](https://github.com/JFormDesigner/FlatLaf/issues/218#issuecomment-1304457193)

**Comment by caduandrade** [comment]
Hi @HiddenMachine3! Sorry, I'm discontinuing this project as there are newer and better ones. 
Ikonli is great.
